version: '3.7'

services:
  api:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/local.env

  page:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/usr/src/app/'
    ports:
      - 3000:80
    environment:
      - NODE_ENV=development
